apiVersion: v1
kind: Service
metadata:
  name: mysql-clusterip
spec:
  type: ClusterIP
  ports:
  - name: "mysql-port"
    protocol: "TCP"
    port: 13306
    targetPort: 3306
  selector:
    app: mysql 
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  # podをアップデートする時の動作を定義
  # Recreateのときはpodは一つしか存在できず、更新すると
  # 古いものが消え新しいものが再度作成される
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: # secretを使ってパスワードを埋め込む
            secretKeyRef:
              name: mysql-secret
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts: # コンテナ内のどのディレクトリにpersistentVolumeをマウントするか
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes: #
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
          # name=mysql-pv-claimを使って、マウントできるPVを探す