apiVersion: v1
kind: Service
metadata:
  name: django-lb
spec:
  type: LoadBalancer
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: django
---
apiVersion: v1
kind: Service
metadata:
  name: django-clusterip
spec:
  type: ClusterIP
  ports:
  - name: "http-port"
    protocol: "TCP"
    port: 80
    targetPort: 8000
  selector:
    app: django
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 3
  selector:
    matchLabels:
      app: django
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: django
        image: "mysite/django:v1"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
          name: django